/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hubertmap;

import hubertmap.model.parser.Parser;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Parser interpreterCSV = new Parser();
        
    }
}
